name = "gravity-blog"
type = "javascript"
account_id = "6cb3cb63c3df5143d124b45a80ab7b95"
workers_dev = true
main = "functions/_worker.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "gravity_affiliate"
database_id = "da05a906-cf21-4717-a96f-c1da3966fd56"

[env.production]
routes = [
  { pattern = "gravity-blog.pages.dev/*", zone_name = "gravity-blog.pages.dev" }
]
